apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/hadi-alnehlawi/nd064_course_1
    targetRevisio: HEAD



  