steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "cleanup"
    entrypoint: 'bash'
    args: ["sed", "'s/APPENGINE_SERVICE_NAME/chr-service/g'", "./${_SCRIPT_URI}"]
    # args: 
    #   - -c
    #   - sed 's/APPENGINE_SERVICE_NAME/chr-service/g' ./${_SCRIPT_URI} 
    #   - |
    #       ${_SCRIPT_URI}
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["cleanup"]
  #   args: ["app", "deploy", "./appengine", "--quiet"]
substitutions:
  _SCRIPT_URI: appengine/scripts/cleanup_last_appengine_build.sh

