steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "cleanup"
    entrypoint: 'bash'
    args: ['appengine/demo.sh']
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["cleanup"]
    args: ["version"]
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["cleanup"]
    args: ["app", "deploy", "./appengine", "--quiet"]
