steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      pwd
      # export VERSIONS_COUNT=$(gcloud app versions list --sort-by=createTime --format=json | jq ' . | length');
      # echo $VERSIONS_COUNT;
      # if [[ $VERSIONS_COUNT == 210 ]]
      # then
      #         echo "deleting the last verion which its count is 210...."
      #         gcloud app versions delete $(gcloud app versions list --sort-by=createTime --limit 1 --format='value(VERSION.ID)') --quiet
      # fi

# steps:
#   - name: 'ubuntu'
#     args: ['ls', '-a']
substitutions:
  _SUB_VALUE: unused
options:
  substitution_option: 'ALLOW_LOOSE'