steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "cleanup"
    entrypoint: 'bash'
    env:
      - "VERSIONS_COUNT=0"
    args: 
    - -c
    - |
        for ID in $(gcloud app versions list --sort-by=createTime --format="value(VERSION.ID)" --service=${_SERVICE_NAME}) )
        do
          (($VERSIONS_COUNT=$VERSIONS_COUNT+1))
        done
        
        echo $VERSIONS_COUNT
        
        
        if [[ $VERSIONS_COUNT == 6 ]] 
        then 
          echo "Deleting the last verion which its count is 200....!!" 
          gcloud app versions delete $(gcloud app versions list --sort-by=createTime --limit 1 --format='value(VERSION.ID)' --service=${_SERVICE_NAME}) --quiet
        fi
    
    # args: 
    #   - -c
    #   - sed 's/APPENGINE_SERVICE_NAME/chr-service/g' ./${_SCRIPT_URI} 
    #   - |
    #       ${_SCRIPT_URI}
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["cleanup"]
  #   args: ["app", "deploy", "./appengine", "--quiet"]
substitutions:
  _SERVICE_NAME: "chr-service"

